### ISSUE TITLE
it doesn't work 

### ISSUE THREAD

**Issue by sakura2333** [Haoming02/sd-webui-memory-release#1]
Thanks for apply this script, but it seems now work.
I run it in ubuntu 22.04 LTS
before I click
![2422616749](https://github.com/Haoming02/sd-webui-memory-release/assets/27041052/9d146184-4f98-40b8-9280-5f909b35e7ea)
after press clean 
![2422616749](https://github.com/Haoming02/sd-webui-memory-release/assets/27041052/ee486e99-0dd6-4e61-aa57-7ad0e5be7a66)
then i press clean with debug option
![image](https://github.com/Haoming02/sd-webui-memory-release/assets/27041052/f8ab55ec-5c98-4aa5-8ef5-d041370547cf)
the bash shows 
<img width="181" alt="image" src="https://github.com/Haoming02/sd-webui-memory-release/assets/27041052/8938f018-2838-4b58-864a-aad845d9a349">
in nvidia-smi.  the memory is still before
![2974568386](https://github.com/Haoming02/sd-webui-memory-release/assets/27041052/5ab9d137-f8aa-4955-a040-97489c62f1ff)

**Comment by Haoming02** [comment]
Well yeah… Most of the time this Extension does absolutely nothing.

The only use case I found was the one after getting OoM as shown in README, ~~which helps nothing anyway as you can just generate normally.~~

**Comment by sakura2333** [comment]
> Well yeah… Most of the time this Extension does absolutely nothing.
> 
> The only use case I found was the one after getting OoM as shown in README, ~which helps nothing anyway as you can just generate normally.~

Thanks for you reply.
emmmm.  I seems must try something other way.
So I update my xform 0.0.17->0.0.2(system selected)
and torch 2.0.0 ->2.0.1
Then it  seems release VRAM automatically.
